version: '3.8'

services:
  frontend:
    build: .
    ports:
      - '5173:80'
    env_file: "../.env"
    volumes:
      - type: bind
        source: ./dist
        target: /usr/local/apache2/htdocs
      - type: bind
        source: ./.htaccess
        target: /usr/local/apache2/htdocs/.htaccess
