name: Main Branch CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate_changes:
    name: Validate Changes
    runs-on: ubuntu-latest
    outputs:
      frontend_changed: ${{ steps.set_outputs.outputs.frontend_changed }}
      service_changed: ${{ steps.set_outputs.outputs.service_changed }}
      service_name: ${{ steps.set_outputs.outputs.service_name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate changed files
        id: set_outputs
        run: |
          CHANGED_FILES=$(git diff --name-only ${{ github.sha }})
          echo "Changed files: $CHANGED_FILES"
          FRONTEND_CHANGED=false
          SERVICE_CHANGED=false
          SERVICE_NAME=""
          for FILE in $CHANGED_FILES; do
            if [[ $FILE == frontend/* ]]; then
              FRONTEND_CHANGED=true
            elif [[ $FILE == services/* ]]; then
              SERVICE=${FILE#services/}  # Remove prefix "services/"
              SERVICE=${SERVICE%%/*}  # Extract service name
              if [[ $SERVICE_NAME == "" ]]; then
                SERVICE_NAME=$SERVICE
                SERVICE_CHANGED=true
              elif [[ $SERVICE_NAME != $SERVICE ]]; then
                echo "Error: Changes span multiple services: $SERVICE_NAME and $SERVICE"
                exit 1
              fi
            else
              echo "Error: Change detected outside of allowed folders (frontend and services): $FILE"
              exit 1
            fi
          done

          if $FRONTEND_CHANGED && $SERVICE_CHANGED; then
            echo "Error: Changes span both frontend and services"
            exit 1
          fi

          echo "frontend_changed=$FRONTEND_CHANGED" >> $GITHUB_OUTPUT
          echo "service_changed=$SERVICE_CHANGED" >> $GITHUB_OUTPUT
          echo "service_name=$SERVICE_NAME" >> $GITHUB_OUTPUT

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: validate_changes
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        if: ${{ needs.validate_changes.outputs.frontend_changed == 'true' }}
        uses: actions/setup-node@v2

      - name: Run npm run lint
        if: ${{ needs.validate_changes.outputs.frontend_changed == 'true' }}
        run: cd frontend && npm install && npm run lint

      - name: Run make lint
        if: ${{ needs.validate_changes.outputs.service_changed == 'true' }}
        run: cd services/${{ needs.validate_changes.outputs.service_name }} && make lint

  format:
    name: Format
    runs-on: ubuntu-latest
    needs: validate_changes
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        if: ${{ needs.validate_changes.outputs.frontend_changed == 'true' }}
        uses: actions/setup-node@v2

      - name: Run npm run format
        if: ${{ needs.validate_changes.outputs.frontend_changed == 'true' }}
        run: cd frontend && npm install && npm run format

      - name: Run make format
        if: ${{ needs.validate_changes.outputs.service_changed == 'true' }}
        run: cd services/${{ needs.validate_changes.outputs.service_name }} && make format

