name: Review Branch CI

on:
  push:
    branches:
      - review

jobs:
  validate_source_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Validate source branch
        run: |
          PR_NUMBER=$(jq -r '.[0].number' <<< "$(gh pr list --base review --json number)")
          if [ -z "$PR_NUMBER" ]; then
            echo "No pull request found for the review branch"
            exit 1
          fi

          SOURCE_BRANCH=$(jq -r '.head.ref' <<< "$(gh pr view $PR_NUMBER --json head)")
          if [ "$SOURCE_BRANCH" != "main" ]; then
            echo "Changes to review branch must come from main branch. Current source branch is $SOURCE_BRANCH"
            exit 1
          fi

  integration_tests:
    runs-on: ubuntu-latest
    needs: validate_source_branch
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run integration tests
        run: npm run test-integration
        env:
          CI: true

  e2e_tests:
    runs-on: ubuntu-latest
    needs: validate_source_branch
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run end-to-end tests
        run: npm run test-e2e
        env:
          CI: true

