FROM golang:1.19 AS build
WORKDIR /go/src
COPY {{sourceFolder}} ./{{sourceFolder}}
COPY main.go .
COPY go.sum .
COPY go.mod .
COPY middleware.go .
COPY utils.go .
COPY .env .

ENV CGO_ENABLED=1

RUN go build -o {{packageName}} .

EXPOSE 8080/tcp
ENTRYPOINT ["./{{packageName}}"]
